# Generated by Django 5.0.6 on 2024-06-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('implementations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='implementation',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='implementation',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='implementation',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='implementation',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='implementation',
            name='name',
            field=models.CharField(default='Default Name', max_length=100),
        ),
    ]
