# Generated by Django 5.0.6 on 2024-06-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('implementations', '0002_remove_implementation_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hardware', models.CharField(max_length=255)),
                ('activity', models.CharField(max_length=255)),
                ('stakeholder', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('camera_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Implementation',
        ),
    ]
